# https://splunk.github.io/docker-splunk/ADVANCED.html#runtime-configuration

splunk:
  conf:
    - key: web
      value:
        directory: /opt/splunk/etc/system/local
        content:
          settings:
            ui_inactivity_timeout: -1
    - key: user-prefs
      value:
        directory: /opt/splunk/etc/system/local
        content:
          general:
            tz: America/Los_Angeles
    - key: inputs
      value:
        directory: /opt/splunk/etc/apps/search/local
        content:
          'monitor:///logs':
            disabled: false
            host: unknown
            host_regex: ^.+/([^_]+)
            sourcetype: sdc_log
            whitelist: \.log$
    - key: props
      value:
        directory: /opt/splunk/etc/apps/search/local
        content:
          sdc_log:
            LINE_BREAKER: ([\r\n]+)\[\d{4}-\d{2}-\d{2}
            NO_BINARY_CHECK: true
            category: Custom
            description: Stamps.com flat file log format
            pulldown_type: 1
            SHOULD_LINEMERGE: false
            disabled: false
            EXTRACT-extract_message: \[[^\]]+?(?<level>\w+)\]\W*(?<message>.*)
            EXTRACT-extract_service: _(?<service>.*)\. in source
            EVAL-_raw: message
            TZ: America/Los_Angeles