#!/bin/bash

# Set permissions on config location so we can write
sudo chmod go+rwx $SPLUNK_HOME/etc/apps/search/

# Copy config files to search application
cp -r ../config/. $SPLUNK_HOME/etc/apps/search/local/

sudo $SPLUNK_HOME/bin/splunk stop
yes | sudo $SPLUNK_HOME/bin/splunk clean eventdata
sudo $SPLUNK_HOME/bin/splunk start